name: CI/CD Pipeline

on: [push]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  integration_pipeline:
    name: Integrating Trivia Fever
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          envkey_TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          envkey_SECRET: ${{ secrets.SECRET }}
          envkey_PORT: ${{ secrets.PORT }}
          envkey_DEBUG: false
          file_name: .env
          directory: server
          fail_on_empty: true
      - name: Npm install client
        working-directory: ./client
        run: npm install
      - name: Npm install server
        working-directory: ./server
        run: npm install
      - name: Lint client
        working-directory: ./client
        run: npm run eslint
      - name: Lint server
        working-directory: ./server
        run: npm run eslint
      - name: Test client
        working-directory: ./client
        run: npm run test
      - name: Test server
        working-directory: ./server
        run: npm run test
  deployment_pipeline:
    name: Deploying Trivia Fever
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Npm install client
        working-directory: ./client
        run: npm install
      - name: Npm install server
        working-directory: ./server
        run: npm install
      - name: Build frontend UI
        working-directory: ./server
        run: npm run build:ui
      - name: Deploy to fly.io
        working-directory: ./server
        run: flyctl deploy --remote-only